name: Test CSS Links on gh-pages

on:
  push:
    branches:
      - gh-pages
  pull_request:
    branches:
      - gh-pages

jobs:
  test-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'  # Specify the Ruby version here

    - name: Install HTML Proofer
      run: gem install html-proofer

    - name: Run HTML Proofer
      run: htmlproofer ./dist --allow-hash-href
